### ISSUE TITLE
Feedback milestone 2

### ISSUE THREAD

**Issue by SuzanaMomo** [data301-2021-summer2/project-group8-project#1]
Hello,

My name is Suzana__ and I will be giving you some feedback on your project.

Overall, the project is a good starting point, but there is some work that needs to be done to elevate this project to our standards so its meets our expectations. 

I have divided up the feedback into several sections so it is easier for you to implement.

## Task 1
- Good
## Task 2
- [x] #2
## Task 3
- [x] #3

## Task 4
- [x] #4
- [ ] Could not find any visualization plots for Maruf's research question (the second research question).

**Comment by AhmadRazaJamal** [comment]
Hi @SuzanaMomo, thanks for writing feedback for our project. I think those were valid points and I had rushed through some sections. I think I have improved my analysis and EDA by leaps and bound. I added lots of stuff and fancied it up, I hope you like it :)).

Please take a look at those changes and let me know if it needs more improvement. 

As for Maruf, I think he had to solve his research question, but he was sick last week so he couldn't do so in a timely fashion. He is working on it as we speak. I think he can better speak on that @marufzubery

**Comment by marufzubery** [comment]
Hello @SuzanaMomo , I was a bit sick last week and preoccupied with personal work. I will work on it over the coming week to bring my part up to to standard and expectations. Thank you for your feed back

**Comment by marufzubery** [comment]
Hello @SuzanaMomo , I was a bit sick last week and preoccupied with personal work. I will work on it over the coming week to bring my part up to to standard and expectations. Thank you for your feed back
